name: Publish Python 🐍 distribution 📦 to TestPyPI and run integration tests

on:
  pull_request:

jobs:
  build-n-publish:
    name: Build project and publish to TestPyPI
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [3.8.10]
        spark: [3.2.1]
    environment:
      name: testpypi
      url: https://test.pypi.org/p/databricks-arc/
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build jar
        uses: ./.github/actions/scala_build
      - name: build python
        uses: ./.github/actions/python_build
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          packages-dir: python/dist/
          repository-url: https://test.pypi.org/legacy/
  run-tests:
    - name: run integration tests
    - needs: build-n-publish
    - steps:
      - name: integration tests
        uses: ./.github/actions/integration_tests
